version: '3.7'

services:
  proxy:
    build:
      context: ./proxy
    ports:
      - ${PROXY_PORT}:8080
    volumes:
      - ./backend:/usr/src/artway
      - backend_static_django:/usr/src/artway/static_django
    depends_on:
      - backend
      - frontend
  frontend:
    build:
      context: ./frontend
      args:
        - FRONTEND_PRODUCTION_URL=${FRONTEND_API_URL}
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/media/:/usr/src/artway/media/
      - backend_static_django:/usr/src/artway/static_django/
    environment:
      BACKEND_DEBUG_MODE: ${BACKEND_DEBUG_MODE}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
      BACKEND_ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}
      DJANGO_SUPERUSER_USERNAME: ${BACKEND_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${BACKEND_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${BACKEND_SUPERUSER_PASSWORD}
      BACKEND_DEFAULT_DB: ${BACKEND_DEFAULT_DB}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  ml:
    build:
      context: ./ml
    environment:
      - BACKEND_DEBUG_MODE=${ML_DEBUG_MODE}
      - BACKEND_SECRET_KEY=${ML_SECRET_KEY}
      - BACKEND_ALLOWED_HOSTS=${ML_ALLOWED_HOSTS}
    depends_on:
      - backend
volumes:
  backend_static_django:
  postgres_data:
